carros/urls.py
from django.urls import path
from . import views

app_name = 'carros'

urlpatterns = [
    path('new/', views.new, name="new"),
    path('<int:pk>/', views.pdp, name="pdp"),
    path('plp/', views.plp, name="plp"),  
    path('finalize/<int:car_id>/', views.finalize , name='finalize'),
    path('edit/<int:pk>/', views.edit, name="edit"),  
]

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
  path('<int:id>/', views.chat, name="detail"),
]

marketplace/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('cars/', include('carros.urls')),
    path('chat/', include('chat.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carros/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.
class Car(models.Model):
  car_model = models.CharField(max_length=255)
  brand = models.CharField(max_length=255)
  year = models.IntegerField()
  mileage=models.IntegerField()
  fuel_type=models.CharField(max_length=2551)
  type = models.CharField(max_length=255)
  price = models.FloatField()
  color = models.CharField(max_length=255)
  image = models.ImageField(upload_to='car_images', blank=True, null=True, default='imagem-padrao.jpeg')
  created_by = models.ForeignKey(User, related_name='cars', on_delete=models.CASCADE)
  description = models.TextField(blank=True, null=True)
  is_sold = models.BooleanField(default=False)
  created_at = models.DateTimeField(auto_now_add=True)



  def __str__(self):
    return self.car_model

carros/forms.py
def validar_dados_carro(data, arquivos=None):
    erros = []

    campos_obrigatorios = [
        'brand', 'car_model', 'mileage', 'year', 'fuel_type',
        'type', 'price', 'color', 'description'
    ]

    for campo in campos_obrigatorios:
        if not data.get(campo):
            erros.append(f'O campo {campo} é obrigatório.')

    try:
        if data.get('year') and (int(data.get('year')) < 1900 or int(data.get('year')) > 2100):
            erros.append('Ano inválido.')
    except ValueError:
        erros.append('Ano deve ser um número.')

    try:
        if data.get('mileage') and int(data.get('mileage')) < 0:
            erros.append('Quilometragem deve ser um número positivo.')
    except ValueError:
        erros.append('Quilometragem deve ser um número.')

    try:
        if data.get('price') and float(data.get('price')) < 0:
            erros.append('Preço deve ser um valor positivo.')
    except ValueError:
        erros.append('Preço deve ser um número válido.')

    if arquivos:
        if not arquivos.get('image'):
            erros.append('A imagem é obrigatória.')

    return erros

carros/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages

from carros.models import Car


@login_required
def new(request):
    if request.method == 'POST':
        car_model = request.POST.get('car_model')
        brand = request.POST.get('brand')
        year = request.POST.get('year')
        color = request.POST.get('color')
        mileage = request.POST.get('mileage')
        fuel_type = request.POST.get('fuel_type')
        type = request.POST.get('type')
        price_str = request.POST.get('price')
        price = float(price_str.replace('.', '').replace(',', '.'))
        description = request.POST.get('description')
        image = request.FILES.get('image')

        Car.objects.create(
            car_model=car_model,
            brand=brand,
            year=year,
            color=color,
            mileage=mileage,
            fuel_type=fuel_type,
            type=type,
            price=price,
            description=description,
            image=image,
            created_by=request.user
        )

        messages.success(request, "Anúncio criado com sucesso!")
        return redirect('home')

    return render(request, 'carros/form.html', {
        'title': 'Novo Anúncio'
    })


@login_required
def edit(request, pk):
    car = get_object_or_404(Car, pk=pk, created_by=request.user)

    if request.method == 'POST':
        car.car_model = request.POST.get('car_model')
        car.brand = request.POST.get('brand')
        car.year = request.POST.get('year')
        car.color = request.POST.get('color')
        car.mileage = request.POST.get('mileage')
        car.fuel_type = request.POST.get('fuel_type')
        car.type = request.POST.get('type')
        price_str = request.POST.get('price')
        car.price = float(price_str.replace('.', '').replace(',', '.'))
        car.description = request.POST.get('description')

        if 'image' in request.FILES:
            car.image = request.FILES['image']

        car.save()
        messages.success(request, "Anúncio atualizado com sucesso!")
        return redirect('carros:pdp', pk=car.id)

    return render(request, 'carros/edit-form.html', {'car': car})


@login_required
def car_list(request):
    carros = Car.objects.filter(created_by=request.user, is_sold=False)
    return render(request, 'carros/description.html', {'carros': carros})


def plp(request):
    search = request.GET.get('search')
    brand = request.GET.get('brand')
    marca = request.GET.get('marca')
    modelo = request.GET.get('modelo')
    ano = request.GET.get('ano')
    cor = request.GET.get('cor')
    quilometragem = request.GET.get('quilometragem')
    combustivel = request.GET.get('combustivel')
    carroceria = request.GET.get('carroceria')
    preco = request.GET.get('preco')

    cars = Car.objects.filter(is_sold=False)

    if search:
        cars = cars.filter(car_model__icontains=search)
    if brand:
        cars = cars.filter(brand=brand)
    if marca:
        cars = cars.filter(brand__icontains=marca)
    if modelo:
        cars = cars.filter(car_model__icontains=modelo)
    if ano:
        cars = cars.filter(year=ano)
    if cor:
        cars = cars.filter(color__icontains=cor)
    if quilometragem:
        cars = cars.filter(mileage=quilometragem)
    if combustivel:
        cars = cars.filter(fuel_type__icontains=combustivel)
    if carroceria:
        cars = cars.filter(type__icontains=carroceria)
    if preco:
        cars = cars.filter(price=preco)

    context = {
        'cars': cars,
        'Marca': Car.objects.values_list('brand', flat=True).distinct(),
        'Modelo': Car.objects.values_list('car_model', flat=True).distinct(),
        'Ano': Car.objects.values_list('year', flat=True).distinct(),
        'Cor': Car.objects.values_list('color', flat=True).distinct(),
        'Quilometragem': Car.objects.values_list('mileage', flat=True).distinct(),
        'Combustível': Car.objects.values_list('fuel_type', flat=True).distinct(),
        'Tipo de Carroceria': Car.objects.values_list('type', flat=True).distinct(),
        'Preço': Car.objects.values_list('price', flat=True).distinct()
    }

    return render(request, 'carros/paginadelistagem.html', context)


def pdp(request, pk):
    car = get_object_or_404(Car, pk=pk)
    return render(request, 'carros/paginadedescricao.html', {'car': car})


@login_required
def finalize(request, car_id):
    car = get_object_or_404(Car, id=car_id)
    if car.created_by == request.user:
        car.is_sold = True
        car.save()
        messages.success(request, "Anúncio marcado como vendido.")
        return HttpResponseRedirect(reverse('carros:pdp', args=[car_id]))
    else:
        messages.error(request, "Você não tem permissão para finalizar este anúncio.")
        return redirect('home')

carros/templates/carros/edit-form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
<div class="px-4">
  <form method="POST" action="." class="max-w-[600px] my-[60px] mx-auto p-6 bg-white rounded-lg" enctype="multipart/form-data">
    <h1 id="atualizar_carro" class="text-2xl text-black text-center">Atualizar carro</h1>
    {% csrf_token %}

    <div class="flex flex-col gap-4">
      <input type="text" name="car_model" value="{{ car.car_model }}" placeholder="Modelo" class="border rounded px-3 py-2" required>
      <input type="text" name="brand" value="{{ car.brand }}" placeholder="Marca" class="border rounded px-3 py-2" required>
      <input type="number" name="year" value="{{ car.year }}" placeholder="Ano" class="border rounded px-3 py-2" required>
      <input type="text" name="color" value="{{ car.color }}" placeholder="Cor" class="border rounded px-3 py-2" required>
      <input type="number" name="mileage" value="{{ car.mileage }}" placeholder="Quilometragem" class="border rounded px-3 py-2" required>
      <input type="text" name="fuel_type" value="{{ car.fuel_type }}" placeholder="Combustível" class="border rounded px-3 py-2" required>
      <input type="text" name="type" value="{{ car.type }}" placeholder="Tipo de carroceria" class="border rounded px-3 py-2" required>
      <input type="number" step="0.01" name="price" value="{{ car.price }}" placeholder="Preço" class="border rounded px-3 py-2" required>
      <textarea name="description" placeholder="Descrição" class="border rounded px-3 py-2" rows="4" required>{{ car.description }}</textarea>
      <input type="file" name="image" class="border rounded px-3 py-2">
    </div>

    <button type="submit" id="botao-criar-produto" class="w-full text-base text-white mt-4 bg-sky-500 hover:bg-sky-600 transition-colors px-4 py-2 rounded-lg">Atualizar produto</button>
  </form>
</div>
{% endblock %}

carros/templates/carros/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
<div class="px-4">
  <form method="POST" action="." class="max-w-[600px] my-[60px] mx-auto p-6 bg-white rounded-lg" enctype="multipart/form-data">
    <h1 class="text-2xl text-black text-center">Criar um anúncio</h1>
    {% csrf_token %}

    <div class="flex flex-col gap-4">
      <input type="text" name="car_model" placeholder="Modelo" class="border rounded px-3 py-2" required>
      <input type="text" name="brand" placeholder="Marca" class="border rounded px-3 py-2" required>
      <input type="number" name="year" placeholder="Ano" class="border rounded px-3 py-2" required>
      <input type="text" name="color" placeholder="Cor" class="border rounded px-3 py-2" required>
      <input type="number" name="mileage" placeholder="Quilometragem" class="border rounded px-3 py-2" required>
      <input type="text" name="fuel_type" placeholder="Combustível" class="border rounded px-3 py-2" required>
      <input type="text" name="type" placeholder="Tipo de carroceria" class="border rounded px-3 py-2" required>

      <div class="relative">
        <span class="absolute inset-y-0 left-0 pl-3 flex items-center text-gray-500">R$</span>
        <input
          type="number"
          step="0.01"
          min="0"
          name="price"
          placeholder="Preço"
          class="pl-10 border rounded px-3 py-2 w-full"
          required>
      </div>

      <textarea name="description" placeholder="Descrição" class="border rounded px-3 py-2" rows="4" required></textarea>
      <input type="file" name="image" class="border rounded px-3 py-2" required>
    </div>

    <button class="w-full text-base text-white mt-4 bg-sky-500 hover:bg-sky-600 transition-colors px-4 py-2 rounded-lg">
      Criar produto
    </button>
  </form>
</div>
{% endblock %}

carros/templates/carros/paginadedescricao.html
]{% extends 'core/base.html' %}
{% load l10n %}  {# Ativa os filtros de localização #}

{% block title %}{{ car.brand }}{% endblock title %}

{% block content %}
<div class="max-w-7xl mx-auto px-6 mt-10">
  <!-- Image gallery -->
  <div class="flex flex-col my-4 md:my-0 md:grid md:grid-cols-2 gap-4">
    <img src="{{ car.image.url }}" alt="{{ car.car_model }}" class="w-full h-full max-h-[500px]">
    <div>
      <h1 class="text-2xl font-bold tracking-tight text-gray-900 sm:text-3xl">{{car.brand}} {{car.car_model}}</h1>

      <p id="descricao_descricao" class="mt-4 text-base text-gray-900">{{ car.description }}</p>

      <div class="grid grid-cols-3 gap-4 my-9">
        <div class="flex flex-col">
          <span class="text-[12px] text-gray-400">Marca</span>
          <strong class="text-2xl">{{ car.brand }}</strong>
        </div>
        <div class="flex flex-col">
          <span class="text-[12px] text-gray-400">Modelo</span>
          <strong class="text-2xl">{{ car.car_model }}</strong>
        </div>
        <div class="flex flex-col">
          <span class="text-[12px] text-gray-400">Ano</span>
          <strong class="text-2xl">{{ car.year }}</strong>
        </div>
        <div class="flex flex-col">
          <span class="text-[12px] text-gray-400">Estado</span>
          <strong class="text-2xl">{{ car.type }}</strong>
        </div>
        <div class="flex flex-col">
          <span class="text-[12px] text-gray-400">Cor</span>
          <strong class="text-2xl">{{ car.color }}</strong>
        </div>
        <div class="flex flex-col">
          <span class="text-[12px] text-gray-400">Quilometragem</span>
          <strong class="text-2xl">{{ car.mileage }}</strong>
        </div>
        <div class="flex flex-col">
          <span class="text-[12px] text-gray-400">Tipo de Combustível </span>
          <strong class="text-2xl">{{ car.fuel_type }}</strong>
        </div>
        <div class="flex flex-col">
          <span class="text-[12px] text-gray-400">Preço</span>
          <strong class="text-2xl">R$ {{ car.price|floatformat:2|localize }}</strong>
        </div>
      </div>

      {% if request.user == car.created_by %}
        <span class="mt-20 text-lg">Você é o dono desse anúncio.</span>
      {% else %}
        <a href="{% url 'chat:detail' car.id %}?buyer={{ request.user.username }}" target="_self"
          class="block mt-10 text-base text-center text-white bg-sky-500 hover:bg-sky-600 transition-colors px-4 py-3 w-full rounded-lg">
          Entrar em contato
        </a>
      {% endif %}

      {% if request.user == car.created_by %}
      <form action="{% url 'carros:finalize' car.id %}" method="post" class="inline">
        {% csrf_token %}
        <button type="submit"
          id="marcar_vendido"
          class="block mt-10 text-base text-center text-white bg-sky-500 hover:bg-sky-600 transition-colors px-4 py-3 w-full rounded-lg">
          Marcar como Vendido
        </button>
      </form>
      {% endif %}

      {% if car.is_sold %}
      <span id="vendido" class="mt-4 px-2 py-1 text-xs text-white bg-red-500 rounded-full">Vendido</span>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

carros/templates/carros/paginadelistagem.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
<form method="GET" action='.' class="bg-white shadow p-2 rounded">
    <div class="grid grid-cols-2 gap-2 mb-2">
      <div>
        <label for="marca" class="block text-sm">Marca:</label>
        <input id="filter_brand" type="text" id="marca" name="marca" class="w-full border border-gray-300 rounded-sm px-2 py-1 text-sm">
      </div>
      <div>
        <label for="modelo" class="block text-sm">Modelo:</label>
        <input id="filter-model" type="text" id="modelo" name="modelo" class="w-full border border-gray-300 rounded-sm px-2 py-1 text-sm">
      </div>
    </div>
    
    <div class="grid grid-cols-2 gap-2 mb-2">
      <div>
        <label for="ano" class="block text-sm">Ano:</label>
        <input type="number" id="ano" name="ano" class="w-full border border-gray-300 rounded-sm px-2 py-1 text-sm">
      </div>
      <div>
        <label for="cor" class="block text-sm">Cor:</label>
        <input type="text" id="cor" name="cor" class="w-full border border-gray-300 rounded-sm px-2 py-1 text-sm">
      </div>
    </div>
    
    <div class="grid grid-cols-2 gap-2 mb-2">
      <div>
        <label for="quilometragem" class="block text-sm">Quilometragem:</label>
        <input type="number" id="quilometragem" name="quilometragem" class="w-full border border-gray-300 rounded-sm px-2 py-1 text-sm">
      </div>
      <div>
        <label for="combustivel" class="block text-sm">Combustível:</label>
        <input type="text" id="combustivel" name="combustivel" class="w-full border border-gray-300 rounded-sm px-2 py-1 text-sm">
      </div>
    </div>
    
    <div class="grid grid-cols-2 gap-2 mb-2">
      <div>
        <label for="carroceria" class="block text-sm">Tipo de Carroceria:</label>
        <input type="text" id="carroceria" name="carroceria" class="w-full border border-gray-300 rounded-sm px-2 py-1 text-sm">
      </div>
      <div>
        <label for="preco" class="block text-sm">Preço:</label>
        <input type="number" id="preco" name="preco" class="w-full border border-gray-300 rounded-sm px-2 py-1 text-sm">
      </div>
    </div>
    
    <button id="botao_filtrar" type="submit" class="bg-blue-500 text-white py-1 px-2 rounded-sm text-sm">Filtrar</button>
  </form>
  

<div class="mx-auto px-6 max-w-7xl my-10">
    <h1 class="text-3xl mb-4">Carros</h1>

    <div class=""mt-6 px-6 py="12 bg-gray-100 rouded-xl">
        
        <div class="grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-3">
            {% for car in cars %}
            <div>
                <a id='descricao-carro' href="{% url 'carros:pdp' car.id %}">
                    <div>
                        <img src="{{ car.image.url }}" class="rounded-t-xl w-full h-[400px]">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 id="nome_carro" class="text-xl">{{ car.brand }} {{ car.car_model }}</h2>
                        <p class="text-black-500 mt-10 text-3xl text-bold">R$ {{ car.price }}</p>
                        <div class="w-full flex justify-between mt-2">
                            <span class="text-gray-400">{{ car.year }}</span>
                            <span class="text-gray-400">{{ car.color }}</span>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}   
        </div>
    </div>
</div>

{% endblock %}